window.VAULT_DATA = (() => {
  const GUIDE_NAMES = {
    prompting: 'AI Prompting Made Simple',
    life: '100 ChatGPT Prompts to Make Life Easier',
    jobs: 'AI Tools for Job Seekers',
    students: 'ChatGPT for Students',
    income: '50 AI Income Ideas + 100 Prompts',
  };

  function createPrompt(id, title, domain, guide, audience, text, tags) {
    return { id, title, domain, guide, audience, text, tags };
  }

  const promptFormula = [
    {
      part: 'Role',
      summary: 'Tell the AI who to be so the response has the right perspective.',
    },
    {
      part: 'Objective',
      summary: 'State exactly what you want created, solved, or improved.',
    },
    {
      part: 'Context',
      summary: 'Share the audience, constraints, inputs, and real-world setting.',
    },
    {
      part: 'Guardrails',
      summary: 'Set tone, limits, format rules, and what to avoid.',
    },
    {
      part: 'Output Check',
      summary: 'Ask for a clear structure plus a quick quality review or next step.',
    },
  ];

  const promptingGuidePrompts = [
    createPrompt(
      'prompting-1',
      'Turn rough notes into a clean action plan',
      'productivity',
      GUIDE_NAMES.prompting,
      ['business', 'consumer'],
      'Act as a project manager. Turn my rough notes into a one-page action plan with priorities, deadlines, blockers, and first three actions. Ask up to three clarifying questions if anything is missing before you draft it.',
      ['planning', 'clarity']
    ),
    createPrompt(
      'prompting-2',
      'Rewrite an email with warmth and confidence',
      'communication',
      GUIDE_NAMES.prompting,
      ['business', 'consumer'],
      'Act as an executive communications coach. Rewrite this email so it sounds warm, clear, and confident without sounding stiff. Keep it under 180 words and include a subject line plus a clear next-step ask.',
      ['email', 'tone']
    ),
    createPrompt(
      'prompting-3',
      'Create a workshop agenda from a goal',
      'business',
      GUIDE_NAMES.prompting,
      ['business', 'community'],
      'Act as a workshop designer. Build a 60-minute session agenda on [topic] for [audience]. Include outcomes, timing, interactive moments, and a closing call to action.',
      ['workshop', 'agenda']
    ),
    createPrompt(
      'prompting-4',
      'Simplify a complex idea for different ages',
      'education',
      GUIDE_NAMES.prompting,
      ['education', 'consumer'],
      'Explain [concept] at four levels: age 8, middle school, high school, and adult beginner. Use simple examples, define key words, and include one quick self-check question for each level.',
      ['teaching', 'explainers']
    ),
    createPrompt(
      'prompting-5',
      'Build a realistic weekly meal plan',
      'home',
      GUIDE_NAMES.prompting,
      ['consumer'],
      'Act as a practical household planner. Build a 7-day family meal plan for [number of people] on a budget of [amount]. Use simple ingredients, one leftover night, and include a shopping list.',
      ['family', 'planning']
    ),
    createPrompt(
      'prompting-6',
      'Generate mock interview practice',
      'career',
      GUIDE_NAMES.prompting,
      ['workforce', 'consumer'],
      'Act as an interview coach. Ask me 10 likely interview questions for a [role] at a [type of company]. After each answer, score me for clarity, evidence, and confidence and suggest a stronger revision.',
      ['interview', 'practice']
    ),
    createPrompt(
      'prompting-7',
      'Create a content batch from one idea',
      'marketing',
      GUIDE_NAMES.prompting,
      ['business'],
      'Act as a content repurposing strategist. Take this core idea and turn it into a LinkedIn post, a TikTok hook list, an email intro, and three carousel slide headlines. Keep the message consistent across formats.',
      ['content', 'repurposing']
    ),
    createPrompt(
      'prompting-8',
      'Plan a community event checklist',
      'community',
      GUIDE_NAMES.prompting,
      ['community', 'business'],
      'Act as an event operations lead. Build a checklist for running a [event type] in [timeframe]. Split it into prep, promotion, day-of, and follow-up tasks with owner suggestions.',
      ['events', 'operations']
    ),
    createPrompt(
      'prompting-9',
      'Upgrade weak resume bullets',
      'career',
      GUIDE_NAMES.prompting,
      ['workforce'],
      'Act as a resume writer. Rewrite these bullets using stronger verbs, measurable outcomes, and ATS-friendly language. Give me a before-and-after version and explain the pattern you used.',
      ['resume', 'ATS']
    ),
    createPrompt(
      'prompting-10',
      'Make a quick research brief',
      'research',
      GUIDE_NAMES.prompting,
      ['business', 'workforce'],
      'Act as a research analyst. Summarize what I need to know about [company, industry, or topic] in one page with key facts, opportunities, risks, and three smart questions to ask next.',
      ['research', 'brief']
    ),
    createPrompt(
      'prompting-11',
      'Draft a parent-school email',
      'parents',
      GUIDE_NAMES.prompting,
      ['consumer', 'education'],
      'Act as a respectful parent advocate. Draft an email to a teacher or school counselor about [issue]. Keep the tone collaborative, clear, and solution-oriented, and end with a suggested next step.',
      ['school', 'email']
    ),
    createPrompt(
      'prompting-12',
      'Turn a budget into smarter choices',
      'finance',
      GUIDE_NAMES.prompting,
      ['consumer', 'business'],
      'Act as a budget coach. Review this list of spending categories and help me find savings, tradeoffs, and one realistic 30-day money improvement plan.',
      ['budget', 'review']
    ),
    createPrompt(
      'prompting-13',
      'Build a 30-day content calendar',
      'marketing',
      GUIDE_NAMES.prompting,
      ['business'],
      'Act as a social strategist. Build a 30-day content calendar for [business type] targeting [audience]. Include platform, topic, hook, CTA, and repurposing notes.',
      ['calendar', 'marketing']
    ),
    createPrompt(
      'prompting-14',
      'Outline a first SOP',
      'operations',
      GUIDE_NAMES.prompting,
      ['business', 'community'],
      'Act as an operations consultant. Turn this repeated process into a simple SOP with purpose, steps, quality checks, owner, and common mistakes to avoid.',
      ['SOP', 'workflow']
    ),
    createPrompt(
      'prompting-15',
      'Convert meeting notes into follow-up',
      'productivity',
      GUIDE_NAMES.prompting,
      ['business'],
      'Act as a chief of staff. Convert these meeting notes into a recap email with decisions, action items, owners, and deadlines. Flag missing owners or unclear decisions.',
      ['meeting', 'follow-up']
    ),
    createPrompt(
      'prompting-16',
      'Draft a customer FAQ section',
      'business',
      GUIDE_NAMES.prompting,
      ['business'],
      'Act as a customer experience writer. Create a concise FAQ for [service or offer] based on these customer concerns. Include objections, expectations, and next-step language.',
      ['FAQ', 'customer']
    ),
    createPrompt(
      'prompting-17',
      'Make a 14-day learning plan',
      'learning',
      GUIDE_NAMES.prompting,
      ['consumer', 'education'],
      'Act as a learning coach. Build a 14-day plan for learning [topic] with 20-minute daily tasks, checkpoints, and practical mini-exercises.',
      ['study', 'learning']
    ),
    createPrompt(
      'prompting-18',
      'Turn an idea into a grant-ready concept',
      'nonprofit',
      GUIDE_NAMES.prompting,
      ['community'],
      'Act as a nonprofit strategist. Turn this raw program idea into a one-page concept note with target audience, need, activities, outcomes, budget categories, and impact measures.',
      ['grant', 'program']
    ),
    createPrompt(
      'prompting-19',
      'Write a stronger speaker bio',
      'brand',
      GUIDE_NAMES.prompting,
      ['business', 'community'],
      'Act as a personal brand editor. Rewrite this speaker bio so it sounds credible, approachable, and event-ready. Give me short, medium, and full versions.',
      ['bio', 'brand']
    ),
    createPrompt(
      'prompting-20',
      'Map a homepage offer story',
      'marketing',
      GUIDE_NAMES.prompting,
      ['business'],
      'Act as a conversion copywriter. Draft homepage sections for [offer] using this structure: problem, promise, proof, process, CTA, and objections.',
      ['website', 'offer']
    ),
    createPrompt(
      'prompting-21',
      'Generate better survey questions',
      'research',
      GUIDE_NAMES.prompting,
      ['business', 'community'],
      'Act as a user researcher. Create 10 survey questions to learn about [audience challenge]. Avoid leading language and make the responses useful for service design.',
      ['survey', 'research']
    ),
    createPrompt(
      'prompting-22',
      'Script a difficult conversation',
      'communication',
      GUIDE_NAMES.prompting,
      ['consumer', 'business'],
      'Act as a communication coach. Help me prepare for a difficult conversation about [topic]. Give me an opening script, likely reactions, calm responses, and a boundary-setting close.',
      ['script', 'conflict']
    ),
    createPrompt(
      'prompting-23',
      'Scope a proposal fast',
      'sales',
      GUIDE_NAMES.prompting,
      ['business'],
      'Act as a consultant. Based on this client need, draft a simple proposal scope with objectives, deliverables, timeline, assumptions, and price framing options.',
      ['proposal', 'sales']
    ),
    createPrompt(
      'prompting-24',
      'Design a time-blocked week',
      'productivity',
      GUIDE_NAMES.prompting,
      ['consumer', 'business'],
      'Act as a productivity strategist. Turn my priorities, meetings, and personal obligations into a balanced weekly time-block plan with focus blocks, admin windows, and recovery space.',
      ['calendar', 'time']
    ),
    createPrompt(
      'prompting-25',
      'Analyze a job description for fit',
      'career',
      GUIDE_NAMES.prompting,
      ['workforce'],
      'Act as a career strategist. Analyze this job description and tell me the top skills, likely pain points, missing keywords in my background, and how to tailor my resume and interview stories.',
      ['job-fit', 'career']
    ),
  ];

  function buildScenarioPrompt(categoryLabel, setup) {
    return `Act as a ${setup.role}. Help me ${setup.goal}. Context: ${setup.context}. Constraints: ${setup.constraints}. Output: ${setup.output}.`;
  }

  const consumerPromptBlueprints = {
    home: [
      ['Weekly meal planner', 'practical household assistant', 'build a 7-day meal plan for my household', 'We are feeding [number] people, trying to stay under [budget], and need easy meals for busy weekdays', 'Use simple ingredients, one leftover night, and no more than 45 minutes of prep on weekdays', 'Return breakfast, lunch, dinner, a shopping list, and a Sunday prep plan'],
      ['Grocery savings reset', 'budget grocery coach', 'lower my grocery spending without making meals feel repetitive', 'My current weekly spending is around [amount] and I shop at [store]', 'Keep the food family-friendly and avoid cutting fresh produce completely', 'Give me 12 savings moves, a sample list, and three swap strategies'],
      ['Cleaning reset plan', 'home systems organizer', 'build a realistic cleaning routine for my home', 'My home has [rooms] and the hardest areas are [areas]', 'The routine has to fit into 20-minute daily blocks and one longer weekly reset', 'Return a daily, weekly, and monthly checklist'],
      ['Pantry dinner ideas', 'frugal meal planner', 'turn my pantry items into dinner ideas', 'I have [ingredients] and need meals for [people]', 'Use low-cost additions only and keep recipes beginner-friendly', 'Give me five dinners, the missing ingredients, and prep notes'],
      ['Family calendar summary', 'executive assistant for families', 'organize a busy family week into one clear plan', 'The week includes [events] for [family members]', 'Highlight conflicts, travel time, and what needs to be packed the night before', 'Return a day-by-day schedule and a checklist'],
      ['Vacation packing list', 'travel organizer', 'create packing lists for a trip', 'We are traveling to [destination] for [days] in [season] with [travelers]', 'Keep luggage light and call out must-have items only', 'Return separate lists for adults, kids, documents, and travel day snacks'],
      ['Emergency prep checklist', 'household readiness planner', 'help my family get more prepared for emergencies', 'We live in [location] and want to prepare for likely disruptions', 'Keep it affordable and prioritize what can be done in one weekend', 'Return a starter checklist, supply priorities, and a 30-day upgrade path'],
      ['Home maintenance rhythm', 'home maintenance planner', 'set up a seasonal maintenance plan', 'My home includes [features] and I tend to forget recurring tasks', 'Keep it simple enough to revisit once per month', 'Return tasks by season with quick notes on why each matters'],
      ['Declutter sprint', 'decluttering coach', 'plan a decluttering sprint for my home', 'The most cluttered spaces are [spaces] and I only have [time] each day', 'Avoid perfectionism and focus on visible wins first', 'Return a 7-day sprint with one bag, one drawer, and one room milestone'],
      ['Birthday party budget', 'celebration planner', 'plan a birthday party that feels thoughtful without overspending', 'The guest count is [number], the age group is [age], and the budget is [amount]', 'Prioritize low-stress options and easy setup', 'Return food, decor, activities, and a spending breakdown'],
      ['Laundry system', 'household operations coach', 'design a laundry routine that prevents pileups', 'My household size is [number] and laundry is hardest on [days]', 'Keep it easy to maintain with labels or baskets if needed', 'Return a weekly cadence, folding rules, and delegation ideas'],
      ['Home office upgrade', 'workspace planner', 'improve my home office setup', 'I work on [tasks] and my current workspace issues are [issues]', 'Keep purchases modest and favor layout changes first', 'Return layout suggestions, equipment priorities, and a focus-friendly routine'],
      ['Pet care schedule', 'pet care coordinator', 'create a care schedule for my pet', 'I have a [pet type] with these needs: [needs]', 'The schedule must work around a full work week', 'Return feeding, exercise, grooming, meds, and backup care reminders'],
      ['Moving checklist', 'moving coordinator', 'create a moving checklist that reduces stress', 'I am moving from [home type] to [new home type] in [timeframe]', 'Prioritize utility transfers, packing flow, and what to do the first 48 hours after moving', 'Return a timeline by week plus a day-of checklist'],
      ['Garden starter plan', 'beginner gardening coach', 'help me start a small garden', 'I have [space type], [sunlight], and want to grow [plants]', 'Keep the plan beginner-friendly and budget-aware', 'Return a starter layout, supplies, watering routine, and first-month schedule'],
      ['Ingredient rescue plan', 'creative home cook', 'turn random ingredients into meals before they expire', 'I need to use [ingredients] soon', 'Avoid complicated cooking steps and long shopping trips', 'Return three meals, one snack, and one freezer option'],
      ['Energy savings audit', 'household efficiency advisor', 'find realistic ways to reduce my energy bill', 'My home type is [type] and my biggest usage concerns are [concerns]', 'Focus on low-cost changes first', 'Return quick wins, seasonal changes, and a 30-day action list'],
      ['Guest room prep', 'hospitality planner', 'prepare my home for overnight guests', 'Guests are arriving in [days] and staying for [nights]', 'Make the plan warm and practical rather than fancy', 'Return room prep, bathroom prep, snacks, and welcome touches'],
      ['Chore rotation', 'family systems coach', 'build a fair household chore rotation', 'My household includes [people and ages]', 'Keep tasks age-appropriate and easy to track', 'Return a weekly chart plus accountability ideas'],
      ['Weekend reset plan', 'life admin organizer', 'create a weekend reset that makes Monday easier', 'My main stress points are [stress points]', 'The reset has to fit into [time] and include rest', 'Return a schedule for home, food, admin, and recovery'],
    ],
    parents: [
      ['Morning routine for kids', 'family routine coach', 'design a calmer morning routine for my kids', 'The household includes [ages] and our biggest morning issue is [issue]', 'Keep steps visual and realistic for school days', 'Return a routine, parent prompts, and a backup plan for rough mornings'],
      ['Bedtime script', 'parenting support coach', 'create a bedtime routine and script', 'My child is [age] and bedtime struggles usually look like [struggle]', 'The routine needs to feel calm, not punitive', 'Return steps, language to use, and what to do when the routine slips'],
      ['After-school snack plan', 'family nutrition planner', 'plan easy after-school snacks', 'I need options for [number] kids with these preferences or allergies: [details]', 'Use low-prep foods and keep the budget reasonable', 'Return a one-week snack menu and shopping list'],
      ['Screen time agreement', 'digital parenting coach', 'draft a family screen time agreement', 'The main device issues are [issues] for kids ages [ages]', 'Balance flexibility with clear consequences', 'Return rules, talking points, and a short family pledge'],
      ['Homework support plan', 'study support coach', 'create a homework support system that reduces stress', 'My child is in [grade] and struggles with [subjects or habits]', 'Avoid turning homework time into constant conflict', 'Return routine ideas, prompts parents can use, and escalation rules'],
      ['Thank-you note helper', 'family etiquette coach', 'help my child write thank-you notes', 'The gifts or support we are thanking people for are [details]', 'Keep the wording age-appropriate and genuine', 'Return three note templates at different age levels'],
      ['Family meeting agenda', 'family facilitator', 'create a family meeting agenda', 'We need to talk about [topic] and include [family members]', 'Keep it short and solution-focused', 'Return a 20-minute agenda, question prompts, and a closing ritual'],
      ['Summer activity calendar', 'youth enrichment planner', 'plan a summer activity calendar', 'The age range is [ages], budget is [amount], and location is [city or region]', 'Mix learning, fun, and low-cost home days', 'Return a weekly plan with themed days and supplies'],
      ['Sibling conflict coaching', 'family communication coach', 'give me scripts for handling sibling conflict', 'Typical fights happen around [issue]', 'The goal is coaching, not lecturing', 'Return parent scripts, repair questions, and prevention habits'],
      ['Parent-teacher conference questions', 'school partnership coach', 'prepare for a parent-teacher conference', 'My child is in [grade] and I want clarity on [concerns]', 'Keep the tone collaborative and respectful', 'Return the top questions, follow-up phrases, and note-taking prompts'],
      ['Travel entertainment pack', 'family travel planner', 'plan a no-chaos travel entertainment kit for kids', 'We are traveling for [hours] with kids ages [ages]', 'Avoid relying only on screens', 'Return activity ideas, packing list, and a timing plan'],
      ['Chore chart system', 'parent operations coach', 'build a chore chart that kids will actually use', 'My kids are [ages] and current chores are [details]', 'Keep it simple and easy to track visually', 'Return roles, rewards or recognition ideas, and reset rules'],
      ['School lunch rotation', 'practical meal planner', 'plan school lunches that are easy to repeat', 'The eater preferences are [details]', 'Use affordable ingredients and avoid overly complex prep', 'Return a two-week rotation and shopping list'],
      ['Emotion check-in prompts', 'child development coach', 'generate daily emotional check-in prompts', 'I want to help my child talk more openly about school and feelings', 'Keep the questions short and age-appropriate', 'Return 15 prompts and tips for using them at dinner or bedtime'],
      ['Teen job search support', 'career-support parent coach', 'help my teenager get ready for their first job search', 'My teen is interested in [interests] and has [experience level]', 'Make the plan confidence-building and beginner-friendly', 'Return resume ideas, practice questions, and a weekly action plan'],
      ['College visit questions', 'family college planning coach', 'prepare smart questions for college visits', 'The student is interested in [majors or experiences]', 'Focus on fit, support, and finances', 'Return categorized questions and a simple note-taking template'],
      ['Allowance plan', 'family finance coach', 'design an allowance or earning system for my child', 'The child is [age] and I want to teach [money habit]', 'Keep it practical and values-based', 'Return a simple structure, rules, and parent talking points'],
      ['Sick day care checklist', 'household care organizer', 'make a sick day home-care checklist', 'The child symptoms or needs are [details]', 'This is for basic home organization, not medical diagnosis', 'Return comfort tasks, school communication reminders, and supply checks'],
      ['Family tech rules', 'digital household advisor', 'create family tech rules we can actually follow', 'Our biggest tension points are [issues]', 'Keep the language clear and not overly strict', 'Return five rules, reasons, and a reset plan after breaks are missed'],
      ['Rainy day activity bank', 'activity planner', 'build a list of low-stress rainy day activities', 'The kids are [ages] and the supplies we already have are [supplies]', 'Mix active, creative, and quiet choices', 'Return 20 ideas sorted by energy level and setup time'],
    ],
    career: [
      ['LinkedIn headline upgrade', 'career brand strategist', 'rewrite my LinkedIn headline so it sounds specific and valuable', 'My target role is [role] and my strengths are [strengths]', 'Avoid buzzword stuffing', 'Return 10 headline options plus one summary line'],
      ['Networking follow-up message', 'professional relationship coach', 'write a follow-up message after a networking conversation', 'I met this person in [context] and want to stay in touch around [topic]', 'Keep the note brief and natural', 'Return two versions: warm and direct'],
      ['Weekly career plan', 'career accountability coach', 'build a weekly plan for my job or career growth goals', 'My priorities are [goals] and available time is [time]', 'Make the plan realistic for a busy week', 'Return daily actions, one stretch goal, and tracking ideas'],
      ['Performance review draft', 'executive coach', 'prepare a strong self-assessment for a performance review', 'My wins include [wins] and my growth areas are [growth areas]', 'Keep the tone confident, not defensive', 'Return a polished draft with evidence-focused bullets'],
      ['Meeting agenda builder', 'team lead', 'create a meeting agenda that drives decisions', 'The meeting is about [topic] with [participants]', 'Keep it under [time] minutes and prevent side-tracks', 'Return agenda sections, timing, and pre-read asks'],
      ['Salary negotiation prep', 'salary negotiation coach', 'prepare me for a compensation conversation', 'The role is [role], market context is [details], and my leverage points are [points]', 'Keep the language professional and collaborative', 'Return talking points, objections, and responses'],
      ['Resume summary writer', 'resume strategist', 'write a resume summary that positions me well', 'My target role is [role] and my differentiators are [points]', 'Keep it concise and ATS-friendly', 'Return three versions with different tones'],
      ['Interview story bank', 'interview coach', 'turn my experience into STAR stories', 'The situations I can use are [situations]', 'Keep each story under two minutes spoken', 'Return six stories with situation, action, result, and lesson'],
      ['Portfolio case study', 'portfolio editor', 'outline a case study for a project I worked on', 'The project was [project] and the outcome was [outcome]', 'Keep the story clear for non-experts too', 'Return sections, headlines, and evidence ideas'],
      ['Skill gap roadmap', 'career planner', 'identify and close my skill gaps for a target role', 'The target role is [role] and my current skill set is [skills]', 'Keep the plan to 60 days', 'Return top gaps, fast learning options, and weekly milestones'],
      ['First 90 days plan', 'new role success coach', 'build a first 90 days plan for a new job', 'The role is [role] and likely priorities are [priorities]', 'Balance learning, relationships, and quick wins', 'Return goals for days 1-30, 31-60, and 61-90'],
      ['Hard conversation email', 'manager communication coach', 'draft a clear email about a difficult workplace issue', 'The issue is [issue] and the desired outcome is [outcome]', 'Keep it respectful and factual', 'Return the email and a suggested subject line'],
      ['Mentor outreach note', 'career relationship strategist', 'write a note asking someone to be a mentor or advisor', 'I admire them for [reason] and want help with [goal]', 'Keep it humble and specific', 'Return a message plus a short follow-up if they say yes'],
      ['Learning roadmap', 'upskilling coach', 'plan my learning path for a new skill', 'The skill is [skill] and I have [time] per week', 'Focus on practical outcomes, not endless theory', 'Return a 30-day roadmap and mini-project ideas'],
      ['Team update rewrite', 'staff communications lead', 'rewrite my team update so it is clearer and more useful', 'The update includes [content]', 'Keep it short and action-oriented', 'Return a rewritten version and a three-part structure I can reuse'],
      ['Career pivot story', 'career narrative coach', 'help me explain a career pivot in a confident way', 'I am moving from [from] to [to]', 'Avoid sounding apologetic', 'Return interview wording, networking wording, and a LinkedIn version'],
      ['Personal brand bio', 'professional bio writer', 'create a short professional bio for me', 'My work focuses on [focus] and I want to be known for [qualities]', 'Keep it versatile enough for events and profiles', 'Return short, medium, and full versions'],
      ['Conference note summary', 'knowledge synthesis assistant', 'turn my conference notes into takeaways', 'My notes are about [topics]', 'Focus on action, not just recap', 'Return key insights, follow-ups, and ideas to apply this month'],
      ['Job description match score', 'job fit analyst', 'compare my background against a job description', 'My experience is [experience] and the job description is [description]', 'Be honest about gaps and strengths', 'Return a match summary, missing pieces, and tailoring advice'],
      ['Job offer decision matrix', 'career decision advisor', 'help me compare job offers or opportunities', 'I am comparing [options] and care most about [priorities]', 'Use both numbers and quality-of-life factors', 'Return a decision table and a recommendation with reasoning'],
    ],
    'small business': [
      ['30-day content plan', 'small business content strategist', 'build a 30-day content plan for my business', 'My business is [business] and audience is [audience]', 'Keep the content practical and repurpose-friendly', 'Return post ideas, hooks, and CTA suggestions'],
      ['Client onboarding email', 'client experience consultant', 'draft a polished onboarding email', 'My service includes [service details] and common client questions are [questions]', 'Keep the tone welcoming and organized', 'Return the email and a next-step checklist'],
      ['Offer positioning refresh', 'offer strategist', 'clarify how to position my offer so it feels more valuable', 'The offer is [offer] and current objections are [objections]', 'Avoid jargon and focus on business outcomes', 'Return a positioning statement, headline, and proof ideas'],
      ['FAQ page draft', 'conversion copywriter', 'draft an FAQ page for my service', 'The service is [service] and buyers usually worry about [worries]', 'Keep answers clear and concise', 'Return 10 FAQs with confident but honest answers'],
      ['Discovery call question bank', 'sales consultant', 'create discovery call questions that uncover real needs', 'My ideal client is [client] and my service solves [problem]', 'Keep questions open-ended and consultative', 'Return questions by stage of the call'],
      ['Proposal outline', 'service proposal writer', 'outline a proposal for a new client', 'The client needs [need] and the likely scope is [scope]', 'Keep it easy to customize', 'Return sections, example language, and a pricing frame'],
      ['Customer persona starter', 'market researcher', 'create a practical customer persona', 'My best buyers seem to be [description]', 'Avoid fluffy demographic stereotypes', 'Return motivations, pain points, triggers, and channels'],
      ['Blog idea generator', 'content marketer', 'generate useful blog ideas for my business', 'My audience struggles with [pain points]', 'Focus on helpful, search-friendly ideas', 'Return 20 ideas with target intent and CTA angle'],
      ['Testimonial request', 'client marketing coach', 'write a testimonial request that clients will actually answer', 'The service delivered [results]', 'Make it easy for the client to respond quickly', 'Return the email and five optional prompts'],
      ['Price objection responses', 'sales messaging coach', 'help me answer price objections', 'Common objections are [objections] for [offer]', 'Keep the language respectful and value-based', 'Return scripts for email, DM, and live conversations'],
      ['Local SEO checklist', 'local marketing advisor', 'create a simple local SEO checklist for my business', 'My business category is [category] and city is [city]', 'Prioritize actions that matter most first', 'Return weekly, monthly, and one-time tasks'],
      ['Workshop outline', 'education marketer', 'turn my expertise into a workshop outline', 'The topic is [topic] and audience is [audience]', 'Design it to lead naturally into a service or program', 'Return agenda, learning outcomes, and CTA options'],
      ['Social media package design', 'agency offer designer', 'package a social media service in a cleaner way', 'My current service includes [details]', 'Keep delivery manageable for one person or a small team', 'Return package levels, deliverables, and positioning notes'],
      ['Referral program idea', 'growth strategist', 'design a referral program for my clients or audience', 'My offer is [offer] and ideal referrers are [people]', 'Keep the incentive easy to explain', 'Return the structure, messaging, and launch plan'],
      ['Product description rewrite', 'ecommerce copywriter', 'rewrite my product descriptions to convert better', 'The product is [product] and the audience cares about [benefits]', 'Focus on clarity over hype', 'Return headline, bullets, and objection handling'],
      ['Email nurture sequence', 'email strategist', 'create a short nurture sequence for leads', 'The lead magnet is [magnet] and the paid offer is [offer]', 'Keep the sequence conversational and useful', 'Return five emails with a CTA progression'],
      ['Intake SOP', 'operations planner', 'turn my client intake into a documented process', 'The current process includes [steps]', 'Make it easy to hand off or automate later', 'Return triggers, steps, templates, and quality checks'],
      ['Lead magnet outline', 'lead generation strategist', 'outline a lead magnet that attracts the right buyers', 'My niche is [niche] and offer is [offer]', 'Make it fast to produce and valuable enough to convert', 'Return title ideas, sections, and next-step CTA'],
      ['Monthly KPI review', 'small business analyst', 'review my simple business KPIs', 'The numbers I track are [metrics]', 'Focus on what decisions the numbers should drive', 'Return insights, concerns, and next-month experiments'],
      ['Sales follow-up flow', 'pipeline coach', 'design a sales follow-up flow after an inquiry or discovery call', 'My buyers usually hesitate because [reasons]', 'Keep it persistent without sounding pushy', 'Return message timing, copy angles, and exit rules'],
    ],
    productivity: [
      ['Daily top three plan', 'personal productivity coach', 'turn my task list into a realistic daily top-three plan', 'My current tasks are [tasks] and available time is [time]', 'Protect focus and avoid overloading the day', 'Return top three priorities, support tasks, and a shutdown checklist'],
      ['Weekly review template', 'executive planning coach', 'create a weekly review process for me', 'I juggle [responsibilities] and often lose track of [issue]', 'Keep the process under 30 minutes', 'Return steps, review questions, and scorecards'],
      ['Project kickoff outline', 'project lead', 'build a simple project kickoff plan', 'The project is [project] with stakeholders [stakeholders]', 'Prioritize alignment, scope clarity, and first milestones', 'Return kickoff agenda, questions, and deliverables'],
      ['Meeting summary pattern', 'meeting operations assistant', 'create a reusable pattern for summarizing meetings', 'The meetings are usually about [topic]', 'Keep it simple enough to use the same day', 'Return a template, examples, and reminder prompts'],
      ['Focus block schedule', 'deep work coach', 'design focus blocks in my week', 'My biggest distractions are [distractions] and peak energy times are [times]', 'Keep the plan doable in a real work week', 'Return block types, timing, and protection rules'],
      ['Habit tracker design', 'behavior coach', 'build a habit tracker for goals I care about', 'The habits are [habits] and my weak point is consistency', 'Avoid making the tracker feel overwhelming', 'Return a tracker layout and weekly review questions'],
      ['Travel work plan', 'mobile work strategist', 'plan a productive work rhythm while traveling', 'I will be traveling for [time] and still need to handle [tasks]', 'Keep bandwidth, time zone, and fatigue in mind', 'Return a schedule, must-do list, and backup communication plan'],
      ['Reading note summary', 'study assistant', 'turn my reading notes into something I can reuse', 'My notes are about [topic]', 'Make the output easy to review later', 'Return key ideas, quotes, and application points'],
      ['Decision journal', 'decision-making coach', 'set up a decision journal for important choices', 'I want to improve decisions around [area]', 'Keep the practice short enough to stick with', 'Return a template and five prompts to review later'],
      ['Task prioritization help', 'workload advisor', 'sort my tasks by urgency and importance', 'My current list is [tasks]', 'Call out what can be delayed, delegated, or dropped', 'Return a ranked plan and reasoning'],
      ['Inbox zero replies', 'email triage assistant', 'draft fast reply patterns for my inbox', 'The recurring email types are [types]', 'Keep each response concise and reusable', 'Return template replies and tagging ideas'],
      ['Brain dump organizer', 'clarity coach', 'organize my brain dump into categories and next steps', 'My raw notes are [notes]', 'Do not lose ideas just because they are messy', 'Return categories, action items, and parking lot ideas'],
      ['Study schedule builder', 'study planner', 'build a study schedule for an upcoming exam', 'The exam date is [date], topics are [topics], and time available is [time]', 'Balance review, practice, and rest', 'Return a calendar and checkpoint plan'],
      ['Recurring project template', 'systems builder', 'create a reusable template for a repeated project', 'The project repeats every [frequency] and includes [steps]', 'Make it easy to clone each time', 'Return phases, checklist items, and timing'],
      ['Goal breakdown', 'accountability coach', 'break a big goal into weekly moves', 'The goal is [goal] and deadline is [deadline]', 'Keep the plan focused on progress over perfection', 'Return milestones, weekly tasks, and a risk list'],
      ['Delegation plan', 'team efficiency coach', 'figure out what and how to delegate', 'My current workload includes [tasks] and available support is [people or vendors]', 'Keep instructions clear enough for handoff', 'Return what to delegate, briefing notes, and quality checks'],
      ['Procrastination reset', 'behavior change coach', 'help me reset when I am procrastinating on something important', 'The avoided task is [task] and the usual trigger is [trigger]', 'Use a supportive tone, not shame', 'Return a five-step reset and a first 15-minute sprint'],
      ['Meeting-free day design', 'calendar strategist', 'help me design one meeting-free day each week', 'My calendar is filled with [meeting types]', 'Protect deep work without harming key relationships', 'Return messaging, boundaries, and alternative meeting windows'],
      ['Side-project roadmap', 'maker coach', 'plan the first month of a side project', 'The side project is [idea] and I can spend [time] per week', 'Focus on momentum and proof of demand', 'Return weekly goals, deliverables, and validation checkpoints'],
      ['Presentation rehearsal helper', 'presentation coach', 'help me rehearse a presentation', 'The audience is [audience] and topic is [topic]', 'Make feedback concrete and improve delivery confidence', 'Return likely questions, transitions, and timing notes'],
    ],
  };

  const consumerPrompts = Object.entries(consumerPromptBlueprints).flatMap(([domain, items]) =>
    items.map((item, index) =>
      createPrompt(
        `${domain.replace(/\s+/g, '-')}-${index + 1}`,
        item[0],
        domain,
        GUIDE_NAMES.life,
        domain === 'small business' ? ['business'] : domain === 'career' ? ['workforce', 'consumer'] : ['consumer'],
        buildScenarioPrompt(domain, {
          role: item[1],
          goal: item[2],
          context: item[3],
          constraints: item[4],
          output: item[5],
        }),
        [domain, 'consumer-pack']
      )
    )
  );

  const jobSeekerPrompts = [
    createPrompt('jobs-1', 'Resume bullet transformer', 'career', GUIDE_NAMES.jobs, ['workforce'], 'Act as an ATS-savvy resume writer. Rewrite my current resume bullets for a [role] so they emphasize outcomes, keywords, and measurable impact. Return before-and-after versions and tell me what changed.', ['resume', 'ATS']),
    createPrompt('jobs-2', 'Job description keyword extractor', 'career', GUIDE_NAMES.jobs, ['workforce'], 'Act as a hiring analyst. Pull the top keywords, skills, and hidden expectations from this job description and group them into must-have, nice-to-have, and likely interview focus areas.', ['keywords', 'analysis']),
    createPrompt('jobs-3', 'ChatGPT voice mock interview', 'career', GUIDE_NAMES.jobs, ['workforce'], 'Act as a live interview coach. Run a spoken mock interview for a [role]. Ask one question at a time, wait for my answer, then give concise feedback on confidence, structure, and evidence before the next question.', ['interview', 'voice']),
    createPrompt('jobs-4', 'Gemini Live practice brief', 'career', GUIDE_NAMES.jobs, ['workforce'], 'Act as a practice session planner. Give me a Gemini Live mock interview setup for [role], including five scenarios, what to listen for in my answers, and how to self-score after the conversation.', ['gemini', 'practice']),
    createPrompt('jobs-5', 'Perplexity company research brief', 'research', GUIDE_NAMES.jobs, ['workforce'], 'Act as a job search researcher. Tell me exactly what to research in Perplexity before an interview with [company], including recent news, product shifts, hiring priorities, and likely team pain points.', ['perplexity', 'research']),
    createPrompt('jobs-6', 'Notion job tracker setup', 'productivity', GUIDE_NAMES.jobs, ['workforce'], 'Act as an operations designer. Create a simple Notion job search dashboard with stages, follow-up reminders, networking fields, and weekly review prompts.', ['notion', 'tracking']),
    createPrompt('jobs-7', 'Canva portfolio starter', 'career', GUIDE_NAMES.jobs, ['workforce'], 'Act as a portfolio coach. Outline a clean Canva portfolio for a [field] professional with sections for projects, outcomes, testimonials, and contact information.', ['canva', 'portfolio']),
    createPrompt('jobs-8', 'Gamma case study deck', 'career', GUIDE_NAMES.jobs, ['workforce'], 'Act as a presentation strategist. Turn one of my work wins into a five-slide Gamma deck that proves how I think, solve problems, and communicate outcomes.', ['gamma', 'deck']),
    createPrompt('jobs-9', 'Salary research summary', 'career', GUIDE_NAMES.jobs, ['workforce'], 'Act as a compensation analyst. Build a salary research summary for [role] in [location] using market range, experience level, company type, and negotiation levers I should mention.', ['salary', 'negotiation']),
    createPrompt('jobs-10', 'Networking DM draft', 'career', GUIDE_NAMES.jobs, ['workforce'], 'Act as a networking strategist. Draft a short message to someone at [company] asking for insight on the role and team without sounding transactional.', ['networking', 'dm']),
    createPrompt('jobs-11', 'Career-change story', 'career', GUIDE_NAMES.jobs, ['workforce'], 'Act as a career narrative coach. Help me explain my move from [previous field] to [target field] in a way that sounds strategic, credible, and future-focused.', ['career-change', 'story']),
    createPrompt('jobs-12', 'Weekly job search sprint', 'productivity', GUIDE_NAMES.jobs, ['workforce'], 'Act as a job search accountability coach. Build a five-day job search sprint with applications, research, networking, interview prep, and review blocks.', ['plan', 'job-search']),
    createPrompt('jobs-13', 'Thank-you email after interview', 'communication', GUIDE_NAMES.jobs, ['workforce'], 'Act as a professional communications coach. Draft a thank-you email after an interview that references the conversation, reinforces fit, and sounds confident.', ['thank-you', 'email']),
    createPrompt('jobs-14', 'Follow-up after rejection', 'communication', GUIDE_NAMES.jobs, ['workforce'], 'Act as a professional relationship coach. Draft a response after a rejection that keeps the relationship warm, asks for feedback, and leaves the door open.', ['follow-up', 'rejection']),
    createPrompt('jobs-15', 'Story bank builder', 'career', GUIDE_NAMES.jobs, ['workforce'], 'Act as an interview prep coach. Help me build a story bank from my experience for leadership, problem-solving, conflict, adaptability, and achievement questions.', ['stories', 'interview']),
    createPrompt('jobs-16', 'Work sample audit', 'career', GUIDE_NAMES.jobs, ['workforce'], 'Act as a hiring manager. Review my current work samples and tell me which ones best prove readiness for [role], what is missing, and how to improve weak spots.', ['portfolio', 'audit']),
    createPrompt('jobs-17', 'Behavioral question generator', 'career', GUIDE_NAMES.jobs, ['workforce'], 'Act as an interviewer. Generate the 15 most likely behavioral questions for a [role] and explain what a strong answer would show.', ['behavioral', 'questions']),
    createPrompt('jobs-18', 'Value proposition statement', 'career', GUIDE_NAMES.jobs, ['workforce'], 'Act as a personal positioning coach. Turn my experience into a concise value proposition I can use in interviews, LinkedIn, and networking calls.', ['positioning', 'brand']),
    createPrompt('jobs-19', 'Reference prep sheet', 'career', GUIDE_NAMES.jobs, ['workforce'], 'Act as a career strategist. Create a short prep sheet I can send to a reference so they know what role I am pursuing, what strengths to highlight, and how to describe our work together.', ['references', 'prep']),
    createPrompt('jobs-20', 'Recruiter outreach script', 'career', GUIDE_NAMES.jobs, ['workforce'], 'Act as a recruiter relationship coach. Draft an outreach note to a recruiter that explains my fit, target role, and why I am worth a conversation.', ['recruiter', 'outreach']),
  ];

  const studentPrompts = [
    createPrompt('students-1', 'Elementary reading buddy', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a friendly reading buddy for a child in grade [grade]. Read this passage with them by summarizing each paragraph, defining tricky words, and asking one comprehension question at a time.', ['elementary', 'reading']),
    createPrompt('students-2', 'Elementary math coach', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a patient math coach. Help a child practice [math topic] using simple examples, step-by-step thinking, and one quick practice problem at a time.', ['elementary', 'math']),
    createPrompt('students-3', 'Elementary curiosity lab', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a curiosity coach. Turn the topic [topic] into a mini learning adventure for an elementary student using simple explanations, a household example, and one hands-on activity.', ['elementary', 'science']),
    createPrompt('students-4', 'Elementary spelling quiz', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a spelling helper. Quiz a student on these words [words] with encouraging feedback, memory tips, and one sentence example per word.', ['elementary', 'spelling']),
    createPrompt('students-5', 'Elementary story starter', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a creative writing helper for a young learner. Give me three story starters about [topic] with simple characters, a problem, and an ending idea.', ['elementary', 'writing']),
    createPrompt('students-6', 'Parent supervision check-in', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a parent support assistant. Help me supervise a child using AI for homework by giving me five questions to ask before they submit their work and three signs the work may be too AI-generated.', ['parent', 'supervision']),
    createPrompt('students-7', 'Middle school study guide', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a middle school study coach. Turn these notes about [topic] into a study guide with key ideas, vocabulary, self-test questions, and one memory trick.', ['middle-school', 'study']),
    createPrompt('students-8', 'Middle school science explainer', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a science tutor for a middle school student. Explain [concept] using plain language, one analogy, and a quick recap quiz.', ['middle-school', 'science']),
    createPrompt('students-9', 'Middle school essay outline', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a writing tutor. Help a middle school student outline an essay on [topic] with an introduction idea, three body points, evidence suggestions, and a conclusion move.', ['middle-school', 'writing']),
    createPrompt('students-10', 'Middle school note cleanup', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a study organizer. Clean up these messy middle school notes by grouping ideas, highlighting important vocabulary, and flagging anything that needs teacher clarification.', ['middle-school', 'notes']),
    createPrompt('students-11', 'Middle school project planner', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a student planner. Break a school project into steps with deadlines, materials, and checkpoints that fit a middle school schedule.', ['middle-school', 'planning']),
    createPrompt('students-12', 'Middle school research questions', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a research starter. Help a middle school student create good research questions about [topic] and suggest what kinds of sources to look for.', ['middle-school', 'research']),
    createPrompt('students-13', 'High school concept explainer', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a high school tutor. Explain [concept] clearly, then connect it to how it may appear on a quiz, essay, or classroom discussion.', ['high-school', 'tutoring']),
    createPrompt('students-14', 'High school scholarship brainstorm', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a scholarship prep coach. Based on this student profile [profile], list scholarship themes, application angles, and story ideas worth developing.', ['high-school', 'scholarships']),
    createPrompt('students-15', 'High school debate prep', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a debate coach. Prepare arguments for and against [topic], include evidence categories to research, and give three rebuttal patterns.', ['high-school', 'debate']),
    createPrompt('students-16', 'High school lab report outline', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a science writing tutor. Help structure a lab report using these observations [observations], including hypothesis, procedure summary, findings, and conclusion language.', ['high-school', 'lab']),
    createPrompt('students-17', 'High school vocabulary sprint', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a vocabulary coach. Build a 15-minute practice sprint for these SAT or class words [words] with definitions, examples, and recall checks.', ['high-school', 'vocabulary']),
    createPrompt('students-18', 'High school time plan', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a student time coach. Build a weekly schedule that balances homework, activities, rest, and college or career prep.', ['high-school', 'planning']),
    createPrompt('students-19', 'College seminar summary', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a college study assistant. Turn these seminar notes into a concise summary with key arguments, definitions, and discussion-ready insights.', ['college', 'seminar']),
    createPrompt('students-20', 'College thesis brainstorm', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as an academic writing coach. Help me turn my topic [topic] into three possible thesis directions with angles, evidence types, and likely counterarguments.', ['college', 'writing']),
    createPrompt('students-21', 'College source comparison', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a research assistant. Compare these two or three sources on [topic] by argument, evidence, limitations, and how I might use each in a paper.', ['college', 'research']),
    createPrompt('students-22', 'College internship reflection', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a career reflection coach. Help me turn an internship experience into resume bullets, interview stories, and a LinkedIn summary.', ['college', 'career']),
    createPrompt('students-23', 'College lecture note cleanup', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as a note-taking assistant. Clean up my lecture notes on [topic], identify the key takeaways, and turn them into review questions.', ['college', 'notes']),
    createPrompt('students-24', 'College exam review grid', 'education', GUIDE_NAMES.students, ['education', 'consumer'], 'Act as an exam prep strategist. Build a review grid for [course] with concepts, confidence score, practice method, and last review date.', ['college', 'exam']),
  ];

  const incomeIdeas = [
    ['service', 'AI audit sprint', 'small businesses', 'Assess current workflows and identify fast automation wins', 'One-time audit + upsell implementation'],
    ['service', 'Prompt coaching sessions', 'solopreneurs', 'Teach practical prompting for daily work tasks', 'Hourly session + follow-up pack'],
    ['service', 'Workflow setup package', 'busy teams', 'Build lightweight AI workflows for meetings, content, and follow-up', 'Setup fee + maintenance'],
    ['service', 'FAQ chatbot starter', 'local service businesses', 'Turn existing website and FAQ content into a chatbot knowledge base', 'Build fee + monthly support'],
    ['service', 'Email automation tune-up', 'coaches and consultants', 'Use AI to improve nurture, onboarding, and sales follow-up flows', 'Audit + implementation'],
    ['service', 'SOP generator service', 'operators and founders', 'Convert verbal or messy processes into clean SOPs and checklists', 'Per-process package'],
    ['service', 'Meeting notes system', 'agency owners', 'Set up AI notes, decisions, and action tracking', 'Implementation fee'],
    ['service', 'Lead magnet buildout', 'experts and creators', 'Turn expertise into guides, prompts, and opt-in assets', 'Project fee + retainer'],
    ['service', 'Customer support macro pack', 'online shops', 'Build high-quality response templates and escalation flows', 'Done-for-you package'],
    ['service', 'Grant research assistant service', 'nonprofits', 'Use AI to support grant prospecting and concept note drafting', 'Monthly retainer'],
    ['content', 'TikTok script studio', 'creators', 'Write batches of hooks and scripts from one content pillar', 'Monthly content package'],
    ['content', 'Faceless YouTube pack', 'side hustlers', 'Generate video angles, scripts, B-roll prompts, and thumbnails', 'Per-channel package'],
    ['content', 'Newsletter ghostwriting', 'founders', 'Turn voice notes and ideas into recurring newsletters', 'Monthly retainer'],
    ['content', 'Blog refresh service', 'small businesses', 'Rewrite old blog posts for better clarity and calls to action', 'Per-post or monthly'],
    ['content', 'Podcast show notes studio', 'podcasters', 'Convert episode transcripts into notes, clips, and promo posts', 'Per-episode package'],
    ['content', 'Pinterest pin kit', 'ecommerce brands', 'Create titles, descriptions, and pin text from product collections', 'Campaign package'],
    ['content', 'Carousel content service', 'experts on LinkedIn and Instagram', 'Transform one idea into educational carousels', 'Per-carousel or monthly'],
    ['content', 'Course outline accelerator', 'coaches', 'Turn expertise into module plans and lesson drafts', 'Project fee'],
    ['content', 'Webinar slide builder', 'consultants', 'Draft webinar scripts and slide outlines with AI', 'Per-webinar package'],
    ['content', 'Ebook repurposing lab', 'authors and speakers', 'Turn ebooks into blogs, reels, and email sequences', 'Repurposing package'],
    ['local', 'Restaurant social calendar', 'restaurants', 'Create a monthly specials and events content plan', 'Monthly retainer'],
    ['local', 'Salon follow-up automation', 'salons and spas', 'Draft appointment reminders and rebooking sequences', 'Setup + support'],
    ['local', 'Realtor listing description studio', 'realtors', 'Create faster, stronger listing copy and neighborhood summaries', 'Per listing or monthly'],
    ['local', 'Daycare parent communication pack', 'daycares', 'Write polished updates, policies, and family reminders', 'Done-for-you package'],
    ['local', 'Dental FAQ assistant', 'dental offices', 'Create web FAQs and front-desk response scripts', 'Project fee'],
    ['local', 'Church announcement assistant', 'churches', 'Produce weekly announcements, event blurbs, and volunteer asks', 'Monthly package'],
    ['local', 'Library workshop program kit', 'libraries', 'Package AI literacy workshops and handouts', 'Program contract'],
    ['local', 'Fitness studio email pack', 'fitness studios', 'Write challenge emails, class promos, and retention nudges', 'Monthly package'],
    ['local', 'Review response service', 'home service businesses', 'Respond to reviews and generate testimonial requests', 'Monthly subscription'],
    ['local', 'Local listing optimization', 'small local businesses', 'Improve profiles, descriptions, and service pages with AI', 'Audit + refresh fee'],
    ['digital', 'Prompt pack store', 'consumers and creators', 'Sell niche prompt packs for jobs, parenting, study, or marketing', 'Digital product sales'],
    ['digital', 'Template bundle shop', 'solopreneurs', 'Sell plug-and-play worksheets, SOPs, and AI frameworks', 'Digital product sales'],
    ['digital', 'AI readiness assessment', 'businesses and nonprofits', 'Productize a scorecard that leads into audits', 'Assessment + upsell'],
    ['digital', 'ROI calculator pack', 'small businesses', 'Sell simple calculators for savings, speed, and revenue impact', 'Template sales'],
    ['digital', 'Workshop slides kit', 'trainers', 'Package reusable decks and facilitator guides', 'Digital download'],
    ['digital', 'Notion dashboard template', 'professionals', 'Sell dashboard templates for job search, content, or AI ops', 'Template sales'],
    ['digital', 'Client intake forms bundle', 'service providers', 'Sell intake forms and qualification workflows', 'Template sales'],
    ['digital', 'AI policy starter pack', 'schools and teams', 'Sell starter policies, guardrails, and implementation checklists', 'Digital product + consulting'],
    ['digital', 'Student study prompt kit', 'students and parents', 'Sell study, note, and review prompts by grade band', 'Low-ticket digital product'],
    ['digital', 'Job seeker prompt bundle', 'job seekers', 'Sell prompt packs for resume, interview, and networking prep', 'Low-ticket digital product'],
    ['freelance', 'Upwork proposal service', 'freelancers', 'Help people create tailored proposals faster with AI', 'Done-for-you service'],
    ['freelance', 'Virtual assistant accelerator', 'virtual assistants', 'Teach VAs to bundle AI-enhanced services', 'Cohort or mini-course'],
    ['freelance', 'Community college AI webinar', 'community colleges', 'Offer entry-level AI workshops for students and staff', 'Workshop fee'],
    ['freelance', 'Corporate lunch-and-learn', 'employers', 'Deliver practical AI training for teams', 'Corporate workshop fee'],
    ['freelance', 'School professional development kit', 'schools', 'Package teacher-facing AI adoption sessions', 'PD contract'],
    ['freelance', 'Nonprofit board briefing', 'nonprofits', 'Deliver board-level AI overview and readiness briefing', 'Consulting fee'],
    ['freelance', 'Membership office hours', 'memberships', 'Run weekly paid office hours with prompts and live help', 'Recurring revenue'],
    ['freelance', 'Certification cohort', 'professionals', 'Lead a paid certification track around safe AI use', 'Cohort tuition'],
    ['freelance', 'Done-with-you implementation sprint', 'small businesses', 'Guide teams through setting up AI processes in a short sprint', 'Sprint fee'],
    ['freelance', 'AI accountability subscription', 'busy professionals', 'Offer monthly check-ins, templates, and goal tracking', 'Subscription'],
  ].map((idea, index) => ({
    id: `income-idea-${index + 1}`,
    category: idea[0],
    title: idea[1],
    audience: idea[2],
    description: idea[3],
    monetization: idea[4],
  }));

  const incomePrompts = incomeIdeas.flatMap((idea, index) => {
    const baseId = index + 1;
    return [
      createPrompt(
        `income-${baseId}-a`,
        `${idea.title} offer design`,
        'income',
        GUIDE_NAMES.income,
        ['business', 'consumer'],
        `Act as a monetization strategist. Help me package an offer around "${idea.title}" for ${idea.audience}. Include the core promise, ideal buyer, starter deliverables, pricing options, and how to create a clear first version fast.`,
        [idea.category, 'offer']
      ),
      createPrompt(
        `income-${baseId}-b`,
        `${idea.title} lead generation plan`,
        'income',
        GUIDE_NAMES.income,
        ['business', 'consumer'],
        `Act as a demand-generation strategist. Create a lead magnet, social post angle, email CTA, and discovery-call hook I can use to sell "${idea.title}". Keep the language practical for ${idea.audience} and tie it to a visible result.`,
        [idea.category, 'lead-gen']
      ),
    ];
  });

  const prompts = [
    ...promptingGuidePrompts,
    ...consumerPrompts,
    ...jobSeekerPrompts,
    ...studentPrompts,
    ...incomePrompts,
  ];

  const resources = [
    {
      id: 'prompting-made-simple',
      title: GUIDE_NAMES.prompting,
      phase: 'Foundation',
      type: 'Guide',
      tier: 'free',
      release: 'Week 1',
      audience: ['consumer', 'business', 'education', 'community'],
      priceLabel: '$0 lead magnet',
      description: 'Entry-point guide that explains why prompts fail, teaches a five-part prompt formula, and gives readers 25 practical prompts they can use the same day.',
      outcomes: ['Explain AI basics in plain English', 'Show five-part prompt formula', 'Provide 25 ready-to-use prompts', 'Upsell strategy session and workshops'],
      modules: ['AI basics and common misconceptions', 'Why prompts fail', 'Five-part formula', 'Before-and-after examples', 'Next-step offers'],
      cta: 'Thank-you page upsell to a $175 strategy session and a corporate workshop inquiry.',
      featuredPromptIds: promptingGuidePrompts.slice(0, 5).map((prompt) => prompt.id),
    },
    {
      id: '100-life-prompts',
      title: GUIDE_NAMES.life,
      phase: 'Foundation',
      type: 'Prompt Pack',
      tier: 'free',
      release: 'Week 1',
      audience: ['consumer', 'workforce', 'business'],
      priceLabel: '$0 lead magnet',
      description: 'Consumer-first prompt pack organized around home, parenting, career, small business, and productivity needs to maximize broad lead capture.',
      outcomes: ['Deliver 100 categorized prompts', 'Drive list growth with high utility', 'Segment subscribers by life context'],
      modules: ['Home prompts', 'Parents prompts', 'Career prompts', 'Small business prompts', 'Productivity prompts'],
      cta: 'Segment leads for consumer, parenting, career, and small business nurture flows.',
      featuredPromptIds: consumerPrompts.slice(0, 5).map((prompt) => prompt.id),
    },
    {
      id: 'job-seeker-ai-tools',
      title: GUIDE_NAMES.jobs,
      phase: 'Foundation',
      type: 'Guide',
      tier: 'free',
      release: 'Week 2',
      audience: ['workforce', 'community', 'education'],
      priceLabel: '$0 workforce lead magnet',
      description: 'Job-search toolkit covering resume upgrades, interview practice, research workflows, organization systems, and portfolio tools for colleges, libraries, and workforce boards.',
      outcomes: ['Map the best AI stack for job seekers', 'Bundle prompts for interviews and resumes', 'Create a route into workforce programming'],
      modules: ['Resume tools', 'Interview practice with voice workflows', 'Research tools', 'Organization in Notion', 'Portfolio builders in Canva and Gamma'],
      cta: 'Bundle into workforce development programming for colleges, libraries, and workforce boards.',
      featuredPromptIds: jobSeekerPrompts.slice(0, 5).map((prompt) => prompt.id),
    },
    {
      id: 'chatgpt-for-students',
      title: GUIDE_NAMES.students,
      phase: 'Foundation',
      type: 'Guide',
      tier: 'free',
      release: 'Week 2',
      audience: ['education', 'consumer', 'community'],
      priceLabel: '$0 family and school lead magnet',
      description: 'Grade-band guide for elementary through college learners with examples for reading, math, note-taking, study guides, and parent supervision.',
      outcomes: ['Adapt AI use by grade band', 'Support students with ethical workflows', 'Equip parents and educators with supervision language'],
      modules: ['Elementary learning support', 'Middle school study support', 'High school research and planning', 'College productivity and writing', 'Parent supervision'],
      cta: 'Funnels into school workshops, family sessions, and library programs.',
      featuredPromptIds: studentPrompts.slice(0, 5).map((prompt) => prompt.id),
    },
    {
      id: 'income-ideas-pack',
      title: GUIDE_NAMES.income,
      phase: 'Foundation',
      type: 'Guide',
      tier: 'starter',
      release: 'Week 3',
      audience: ['business', 'consumer', 'workforce'],
      priceLabel: 'Included in Starter Vault',
      description: 'Side-hustle and entrepreneurial playbook with 50 income ideas and 100 prompts spanning services, content creation, local business offers, digital products, and freelancing.',
      outcomes: ['Give readers 50 monetization angles', 'Provide 100 prompts to package and market offers', 'Feed into consulting and cohort offers'],
      modules: ['Service-based offers', 'Content creation businesses', 'Local business services', 'Digital products', 'Freelancing and education'],
      cta: 'Anchor the $47 Starter Vault tripwire and feed paid implementation offers.',
      featuredPromptIds: incomePrompts.slice(0, 5).map((prompt) => prompt.id),
    },
    {
      id: 'employer-skills-2026',
      title: 'AI Skills Employers Want in 2026',
      phase: 'Premium',
      type: 'Research Guide',
      tier: 'starter',
      release: 'Phase 2',
      audience: ['workforce', 'education', 'business'],
      priceLabel: 'Premium guide',
      description: 'Hiring-trend themed guide positioned for workforce programming, employer outreach, and career services packaging.',
      outcomes: ['Translate hiring language into training offers', 'Support workforce boards and colleges', 'Create employer-facing workshops'],
      modules: ['Skill clusters', 'Use-case scenarios', 'Training recommendations', 'Employer program tie-ins'],
      cta: 'Use as a premium workforce program seed and employer briefing tool.',
      featuredPromptIds: jobSeekerPrompts.slice(5, 10).map((prompt) => prompt.id),
    },
    {
      id: 'prompt-engineering-real-life',
      title: 'Prompt Engineering for Real Life',
      phase: 'Premium',
      type: 'Workbook',
      tier: 'starter',
      release: 'Phase 2',
      audience: ['business', 'consumer', 'education'],
      priceLabel: 'Premium workbook',
      description: 'Expanded workbook with advanced prompting patterns, exercises, reflection prompts, and applied practice for real-world tasks.',
      outcomes: ['Extend the foundation guide', 'Create a stronger paid workbook', 'Support workshops and office hours'],
      modules: ['Advanced prompting patterns', 'Revision loops', 'Use-case drills', 'Prompt scoring'],
      cta: 'Bundle into workshops, cohort programs, and VIP content.',
      featuredPromptIds: promptingGuidePrompts.slice(10, 15).map((prompt) => prompt.id),
    },
    {
      id: 'make-money-using-ai',
      title: 'Make Money Using AI (No Skills Needed)',
      phase: 'Premium',
      type: 'Guide',
      tier: 'starter',
      release: 'Phase 2',
      audience: ['consumer', 'business'],
      priceLabel: 'Premium consumer funnel',
      description: 'Consumer-friendly monetization guide designed to bridge lead magnets into consulting packages, implementation sprints, and memberships.',
      outcomes: ['Increase consumer conversion rate', 'Package service-based upsells', 'Create a money-focused entry point'],
      modules: ['Fast-start services', 'Simple digital products', 'Client acquisition basics', 'Offer packaging'],
      cta: 'Use in paid ads and content funnels that lead into consulting.',
      featuredPromptIds: incomePrompts.slice(20, 25).map((prompt) => prompt.id),
    },
    {
      id: 'claude-prompts-membership',
      title: '1000+ Claude Prompts',
      phase: 'Premium',
      type: 'Membership Library',
      tier: 'vip',
      release: 'Phase 2',
      audience: ['business', 'consumer', 'workforce'],
      priceLabel: 'VIP-only library',
      description: 'High-volume prompt membership content that differentiates the vault from free resources and supports recurring subscription value.',
      outcomes: ['Create exclusive membership depth', 'Differentiate from free ChatGPT content', 'Encourage retention via weekly updates'],
      modules: ['Business prompt banks', 'Writing workflows', 'Research prompts', 'Advanced role-based prompts'],
      cta: 'Primary recurring-content pillar for paid membership.',
      featuredPromptIds: promptingGuidePrompts.slice(15, 20).map((prompt) => prompt.id),
    },
    {
      id: 'ai-readiness-scorecard',
      title: 'AI Readiness Scorecard',
      phase: 'Expansion',
      type: 'Assessment',
      tier: 'starter',
      release: 'After launch',
      audience: ['business', 'community', 'education'],
      priceLabel: 'Assessment + upsell',
      description: 'Self-serve scorecard that translates guide usage into maturity signals, opportunities, and next-step recommendations.',
      outcomes: ['Drive audit conversations', 'Capture better lead data', 'Bridge content to consulting'],
      modules: ['Usage questions', 'Policy questions', 'Workflow questions', 'Next-step mapping'],
      cta: 'Lead into AI audits and readiness consulting.',
      featuredPromptIds: promptingGuidePrompts.slice(20, 23).map((prompt) => prompt.id),
    },
    {
      id: 'roi-calculator-pack',
      title: 'ROI Calculator Pack',
      phase: 'Expansion',
      type: 'Template Pack',
      tier: 'starter',
      release: 'After launch',
      audience: ['business', 'community'],
      priceLabel: 'Template bundle',
      description: 'Calculator templates that estimate time saved, workflow improvements, and revenue impact from AI use cases.',
      outcomes: ['Support consulting sales', 'Create a paid template asset', 'Improve business case clarity'],
      modules: ['Time savings calculator', 'Lead conversion calculator', 'Workshop ROI calculator'],
      cta: 'Bundle with audits, proposals, and premium templates.',
      featuredPromptIds: jobSeekerPrompts.slice(10, 13).map((prompt) => prompt.id),
    },
    {
      id: 'ai-audit-sprint',
      title: 'AI Audit Sprint',
      phase: 'Expansion',
      type: 'Service',
      tier: 'vip',
      release: 'After launch',
      audience: ['business', 'community', 'education'],
      priceLabel: 'High-ticket service',
      description: 'Sprint-based audit offer that evaluates readiness, workflow opportunities, governance gaps, and implementation priorities.',
      outcomes: ['Create a premium consulting ladder', 'Turn guide completion into service sales', 'Generate enterprise-style engagements'],
      modules: ['Discovery', 'Workflow mapping', 'Readiness scoring', 'Action plan'],
      cta: 'Primary route into higher-tier consulting packages.',
      featuredPromptIds: incomePrompts.slice(40, 45).map((prompt) => prompt.id),
    },
    {
      id: 'certified-user-program',
      title: 'AI with Tracy Certified User Program',
      phase: 'Expansion',
      type: 'Certification',
      tier: 'vip',
      release: 'After launch',
      audience: ['business', 'education', 'workforce'],
      priceLabel: 'Certification cohort',
      description: 'Certification path that combines coursework, prompts, workshops, and implementation tasks into a credibility-building program.',
      outcomes: ['Raise perceived enterprise value', 'Create community and retention', 'Support workforce and team programs'],
      modules: ['Core AI fluency', 'Prompting assessments', 'Applied projects', 'Certification review'],
      cta: 'Use for cohort launches, school partnerships, and memberships.',
      featuredPromptIds: studentPrompts.slice(18, 22).map((prompt) => prompt.id),
    },
    {
      id: 'workshop-replay-vault',
      title: 'Workshop Replay Vault',
      phase: 'Expansion',
      type: 'Course Library',
      tier: 'vip',
      release: 'After launch',
      audience: ['consumer', 'business', 'education', 'community'],
      priceLabel: 'VIP replay library',
      description: 'Centralized home for webinar replays, workshop decks, facilitator notes, and downloadable exercises.',
      outcomes: ['Increase membership value', 'Repurpose workshops into durable assets', 'Create a deeper content moat'],
      modules: ['Replays', 'Slides', 'Worksheets', 'Action plans'],
      cta: 'Key retention driver inside the paid membership area.',
      featuredPromptIds: promptingGuidePrompts.slice(5, 8).map((prompt) => prompt.id),
    },
  ];

  const membershipTiers = [
    {
      id: 'free',
      name: 'Free Explorer',
      price: '$0',
      summary: 'Lead capture tier for broad audience growth and nurture.',
      bestFor: 'First-time visitors, consumers, students, families, and community partners.',
      includes: ['AI Prompting Made Simple', '100 ChatGPT Prompts preview access', 'Selected student and job-seeker content', 'Lead nurture sequence'],
      cta: 'Set current tier',
    },
    {
      id: 'starter',
      name: 'Starter Vault',
      price: '$47 launch / $197 regular',
      summary: 'Tripwire bundle built around the five foundation guides.',
      bestFor: 'Serious leads who want practical prompts, playbooks, and faster implementation.',
      includes: ['All five foundation resources', 'Bonus prompt packs', 'Strategy session discount', 'Priority workshop announcements'],
      cta: 'Set current tier',
    },
    {
      id: 'vip',
      name: 'VIP Advisory',
      price: 'Custom / premium membership',
      summary: 'High-touch access for recurring content, certification, and consulting expansion.',
      bestFor: 'Organizations, teams, and buyers moving from guides into implementation.',
      includes: ['Premium guides and Claude prompt library', 'Workshop replay vault', 'Office hours and community access', 'Assessment and audit pathways'],
      cta: 'Set current tier',
    },
  ];

  const courses = [
    {
      id: 'course-1',
      title: 'AI Job Seeker Bootcamp',
      audience: 'Workforce boards, colleges, libraries',
      summary: 'Four-part bootcamp covering resume tools, research, interview practice, portfolio building, and follow-up systems.',
      outcome: 'Bundle the guide into a contract-ready workforce program.',
    },
    {
      id: 'course-2',
      title: 'ChatGPT for Students and Families',
      audience: 'Parents, schools, libraries',
      summary: 'Family-facing training series on ethical AI use, grade-band workflows, and supervision.',
      outcome: 'Turn the student guide into repeatable school and community programming.',
    },
    {
      id: 'course-3',
      title: 'Small Business AI Revenue Lab',
      audience: 'Entrepreneurs and local businesses',
      summary: 'Hands-on workshop on prompts, lead magnets, automation, and offer packaging.',
      outcome: 'Feeds audits, setup sprints, and retainer offers.',
    },
    {
      id: 'course-4',
      title: 'Library and Nonprofit AI Launch Series',
      audience: 'Community organizations',
      summary: 'Workshop format designed for public-facing organizations introducing AI responsibly.',
      outcome: 'Positions Tracy for community contracts and readiness assessments.',
    },
    {
      id: 'course-5',
      title: 'Certified User Cohort',
      audience: 'Professionals and teams',
      summary: 'Cohort-based certification combining workshops, assignments, office hours, and implementation tasks.',
      outcome: 'Recurring premium offer with strong retention potential.',
    },
  ];

  const tools = [
    {
      id: 'tool-chatgpt',
      name: 'ChatGPT',
      category: 'General assistant',
      audiences: ['consumer', 'workforce', 'education', 'business'],
      rating: 5,
      summary: 'Primary engine for prompting, drafting, ideation, interview prep, and guide creation.',
      tutorial: 'Use for foundational prompting, content generation, mock conversations, and rapid first drafts.',
      monetization: 'Core tool across nearly every vault asset and training offer.',
      link: 'https://chatgpt.com/',
    },
    {
      id: 'tool-claude',
      name: 'Claude',
      category: 'Writing and analysis',
      audiences: ['business', 'workforce'],
      rating: 4,
      summary: 'Strong fit for long-form drafting, document analysis, and premium prompt library differentiation.',
      tutorial: 'Position it inside the VIP library for long-context workflows and refined writing.',
      monetization: 'Supports premium prompt memberships and comparison workshops.',
      link: 'https://claude.ai/',
    },
    {
      id: 'tool-perplexity',
      name: 'Perplexity',
      category: 'Research',
      audiences: ['workforce', 'business', 'education'],
      rating: 4,
      summary: 'Fast research assistant for interview prep, market scanning, and source discovery.',
      tutorial: 'Use it for job seeker research briefs and business discovery prep.',
      monetization: 'Useful in workforce programming and research-heavy consulting.',
      link: 'https://www.perplexity.ai/',
    },
    {
      id: 'tool-notion',
      name: 'Notion',
      category: 'Organization',
      audiences: ['workforce', 'business', 'education'],
      rating: 4,
      summary: 'Source of truth for content, prompt organization, and job search or client dashboards.',
      tutorial: 'Use as the internal operating system behind the vault and assessments.',
      monetization: 'Template sales and implementation sprints.',
      link: 'https://www.notion.so/',
    },
    {
      id: 'tool-gamma',
      name: 'Gamma',
      category: 'Presentations',
      audiences: ['business', 'workforce', 'education'],
      rating: 4,
      summary: 'Fast slide and guide drafting engine for workshops, prompt packs, and client decks.',
      tutorial: 'Convert guides into slide decks and webinar assets quickly.',
      monetization: 'Supports workshops, webinars, and client presentations.',
      link: 'https://gamma.app/',
    },
    {
      id: 'tool-canva',
      name: 'Canva',
      category: 'Design',
      audiences: ['consumer', 'business', 'education'],
      rating: 4,
      summary: 'Visual polish layer for guides, social posts, workbooks, and portfolio assets.',
      tutorial: 'Use after draft generation for clean lead magnets and social media repurposing.',
      monetization: 'Improves conversion of digital products and portfolio services.',
      link: 'https://www.canva.com/',
    },
    {
      id: 'tool-notebooklm',
      name: 'NotebookLM',
      category: 'Knowledge synthesis',
      audiences: ['education', 'business', 'community'],
      rating: 4,
      summary: 'Useful for summarizing source material, generating Q and A, and building study or research support assets.',
      tutorial: 'Helpful for schools, workforce programs, and guide development workflows.',
      monetization: 'Can underpin research-driven premium assets and study supports.',
      link: 'https://notebooklm.google.com/',
    },
    {
      id: 'tool-gemini',
      name: 'Gemini Live',
      category: 'Voice practice',
      audiences: ['workforce', 'education'],
      rating: 4,
      summary: 'Voice-first practice environment for mock interviews, presentations, and language rehearsal.',
      tutorial: 'Feature it prominently in the job seeker and student practice workflows.',
      monetization: 'Great differentiator for workforce and student training.',
      link: 'https://gemini.google.com/',
    },
    {
      id: 'tool-lovable',
      name: 'Lovable',
      category: 'App prototyping',
      audiences: ['business'],
      rating: 3,
      summary: 'Useful example in the tools directory for turning ideas into lightweight apps quickly.',
      tutorial: 'Position as a prototype tool for founders exploring productized services.',
      monetization: 'Good add-on reference in premium and business-facing content.',
      link: 'https://lovable.dev/',
    },
    {
      id: 'tool-sora',
      name: 'Sora',
      category: 'Video generation',
      audiences: ['business', 'consumer'],
      rating: 3,
      summary: 'Reference tool for future visual storytelling, promo content, and high-end brand experiments.',
      tutorial: 'Use in future content workflows and high-visibility campaign ideation.',
      monetization: 'Potential premium add-on for content creation offers.',
      link: 'https://openai.com/sora',
    },
    {
      id: 'tool-grok',
      name: 'Grok',
      category: 'Idea generation',
      audiences: ['consumer', 'business'],
      rating: 3,
      summary: 'Optional angle for alternate prompt testing, social ideation, and comparison content.',
      tutorial: 'Use for comparison tutorials rather than core production.',
      monetization: 'Supports tool-review and affiliate content expansion.',
      link: 'https://grok.com/',
    },
    {
      id: 'tool-hubspot',
      name: 'HubSpot',
      category: 'CRM and nurture',
      audiences: ['business', 'community'],
      rating: 5,
      summary: 'CRM backbone for lead routing, segmentation, pipeline tracking, and nurture automation.',
      tutorial: 'Connect forms, guides, and session booking into one lifecycle.',
      monetization: 'Essential to converting content consumption into consulting revenue.',
      link: 'https://www.hubspot.com/',
    },
  ];

  const roadmap = [
    {
      title: 'Week 1',
      focus: 'Launch the universal lead magnets.',
      items: ['AI Prompting Made Simple', '100 ChatGPT Prompts to Make Life Easier', 'Thank-you page with $175 strategy upsell'],
    },
    {
      title: 'Week 2',
      focus: 'Move into workforce and education audiences.',
      items: ['AI Tools for Job Seekers', 'ChatGPT for Students', 'Repurpose into social, email, and workshop slides'],
    },
    {
      title: 'Week 3',
      focus: 'Monetize with the tripwire bundle.',
      items: ['50 AI Income Ideas + 100 Prompts', 'Starter Vault bundle at $47', 'Segment serious leads for consulting'],
    },
    {
      title: 'Phase 2',
      focus: 'Expand into premium research, memberships, and enterprise-style offers.',
      items: ['Employer skills guide', 'Prompt engineering workbook', 'Claude membership content', 'Readiness assessments and audits'],
    },
  ];

  const insights = [
    {
      title: 'Decision check',
      summary: 'Build the vault first so every new guide has a home, a login path, and data capture from day one.',
    },
    {
      title: 'Risk / blind spot',
      summary: 'Over-producing PDFs without platform infrastructure scatters assets, weakens follow-up, and slows revenue learning.',
    },
    {
      title: 'Tool recommendation',
      summary: 'Use ChatGPT for research and content generation, Codex for platform implementation, Notion for source-of-truth, and HubSpot for CRM.',
    },
    {
      title: 'OCI / GenAI alignment',
      summary: 'Every guide can become an AI asset tied to readiness scoring, audits, action plans, and enterprise consulting pathways.',
    },
  ];

  const automations = [
    {
      id: 'automation-1',
      title: 'Lead capture to HubSpot',
      owner: 'Harper + Ethan',
      status: 'Ready for connector wiring',
      outcome: 'Every form submission becomes a segmented CRM record.',
      steps: ['Capture email, segment, and selected guide', 'Apply lifecycle and audience tags', 'Trigger welcome sequence'],
    },
    {
      id: 'automation-2',
      title: 'Vault access provisioning',
      owner: 'Ethan + Codex',
      status: 'Modeled in app',
      outcome: 'Lead capture routes users into free, starter, or VIP access paths.',
      steps: ['Assign tier', 'Unlock matching content', 'Store progress and bookmarks'],
    },
    {
      id: 'automation-3',
      title: 'Segmented nurture sequences',
      owner: 'Olivia + Harper',
      status: 'Content plan seeded',
      outcome: 'Consumers, job seekers, students, and small businesses receive relevant follow-up.',
      steps: ['Welcome email', 'Guide follow-up', 'Tripwire offer', 'Workshop or session CTA'],
    },
    {
      id: 'automation-4',
      title: 'Strategy session booking handoff',
      owner: 'Harper',
      status: 'CTA ready',
      outcome: 'Qualified readers move from content to a paid strategy call quickly.',
      steps: ['Thank-you page offer', 'Calendar link', 'Pre-call questionnaire'],
    },
    {
      id: 'automation-5',
      title: 'Membership and drip content',
      owner: 'Ethan + Codex',
      status: 'Roadmapped',
      outcome: 'Starter and VIP buyers get gated content, release cadences, and upgrade prompts.',
      steps: ['Payment confirmation', 'Tier upgrade', 'Replay and premium release notifications'],
    },
    {
      id: 'automation-6',
      title: 'Assessment to audit funnel',
      owner: 'Marcus + Harper',
      status: 'Roadmapped',
      outcome: 'Readiness scores turn passive readers into consulting prospects.',
      steps: ['Run assessment', 'Generate maturity summary', 'Recommend audit sprint or workshop'],
    },
  ];

  const assessments = [
    {
      id: 'assessment-1',
      title: 'AI readiness score',
      audience: 'Businesses and nonprofits',
      summary: 'Measures strategy, workflow readiness, team habits, governance, and next-step urgency.',
      output: 'Score, risk flags, and recommended service path.',
    },
    {
      id: 'assessment-2',
      title: 'Prompt confidence score',
      audience: 'Consumers and professionals',
      summary: 'Helps users understand whether they are prompting reactively or strategically.',
      output: 'Skill score plus workbook and workshop recommendations.',
    },
    {
      id: 'assessment-3',
      title: 'Workforce AI fluency check',
      audience: 'Job seekers and colleges',
      summary: 'Assesses job-search AI habits, research skills, interview readiness, and portfolio confidence.',
      output: 'Training gaps and next-step modules.',
    },
    {
      id: 'assessment-4',
      title: 'School and library program fit',
      audience: 'Schools and libraries',
      summary: 'Screens institutions for the right entry workshop, family session, or staff training sequence.',
      output: 'Recommended program track and implementation notes.',
    },
  ];

  const revenueLadders = [
    {
      id: 'ladder-1',
      title: 'Consumer ladder',
      summary: 'Broad lead magnets become paid bundles, then strategy help.',
      steps: ['Free guide', '$47 Starter Vault', '$175 strategy session', 'VIP or implementation support'],
    },
    {
      id: 'ladder-2',
      title: 'Workforce ladder',
      summary: 'Job-seeker assets support institutional contracts and premium programming.',
      steps: ['Free job-seeker guide', 'Workshop or bootcamp', 'Board or college contract', 'Readiness consulting'],
    },
    {
      id: 'ladder-3',
      title: 'Education ladder',
      summary: 'Student and parent content becomes family programs and school PD.',
      steps: ['Free student guide', 'Library or parent workshop', 'School staff training', 'Certification or implementation'],
    },
    {
      id: 'ladder-4',
      title: 'Business ladder',
      summary: 'Prompt and monetization assets move buyers into audits and setup sprints.',
      steps: ['Free prompting guide', 'Starter Vault', 'AI audit sprint', 'Retainer or VIP membership'],
    },
    {
      id: 'ladder-5',
      title: 'Community ladder',
      summary: 'Community-facing resources grow into nonprofit, church, and library engagements.',
      steps: ['Free community resource', 'Program briefing', 'Workshop series', 'Readiness assessment and consulting'],
    },
  ];

  const team = [
    {
      name: 'Ava',
      role: 'Resource Architect',
      scope: 'Creates guides, workbooks, prompt packs, templates, and certification materials.',
    },
    {
      name: 'Marcus',
      role: 'Market Researcher',
      scope: 'Researches workforce trends, industries, funding, and AI opportunity maps.',
    },
    {
      name: 'Olivia',
      role: 'Content Repurposer',
      scope: 'Turns every guide into TikTok scripts, blog posts, emails, and workshop decks.',
    },
    {
      name: 'Harper',
      role: 'Monetization Strategist',
      scope: 'Designs lead magnets, tripwires, membership offers, pricing, and nurture flows.',
    },
    {
      name: 'Ethan',
      role: 'Platform Builder',
      scope: 'Writes specs, shapes product requirements, and translates strategy into build tasks.',
    },
    {
      name: 'Codex',
      role: 'Development Executor',
      scope: 'Builds the vault, dashboards, prompt systems, automations, and the delivery infrastructure.',
    },
  ];

  const dashboard = {
    metrics: [
      { label: 'Resources seeded', value: resources.length, note: 'Foundation, premium, and expansion assets' },
      { label: 'Prompts loaded', value: prompts.length, note: 'Ready for filter, favorite, and copy workflows' },
      { label: 'Automations mapped', value: automations.length, note: 'CRM, access, nurture, booking, and audit flows' },
      { label: 'Revenue ladders', value: revenueLadders.length, note: 'Consumer, workforce, education, business, community' },
    ],
    funnel: [
      { label: 'Lead magnet visitors', value: 1000, percent: 100 },
      { label: 'Vault sign-ups', value: 250, percent: 25 },
      { label: 'Starter Vault buyers', value: 35, percent: 14 },
      { label: 'Strategy session bookings', value: 9, percent: 3.6 },
      { label: 'Consulting opportunities', value: 3, percent: 1.2 },
    ],
  };

  return {
    promptFormula,
    prompts,
    resources,
    membershipTiers,
    courses,
    tools,
    roadmap,
    insights,
    automations,
    assessments,
    revenueLadders,
    team,
    dashboard,
    incomeIdeas,
  };
})();
